import { useMemo } from "react";
import Plot from "react-plotly.js";
import { useAppStore } from "../../store/appStore";

export default function PVCurvePlot() {
  const result = useAppStore((s) => s.latestResult);
  const plotPath = useAppStore((s) => s.latestPlotPath);
  const isDark = useAppStore((s) => s.isDark);

  const { data, layout } = useMemo(() => buildPlot(result, isDark), [result, isDark]);

  if (!result) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-center py-12 px-6 select-none">
        <div className="text-4xl mb-3">📈</div>
        <p className="text-sm text-gray-400 dark:text-gray-500">
          PV curve will appear here after generation
        </p>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-4 p-4 h-full overflow-y-auto">
      {/* Plotly chart */}
      <div className="rounded-xl overflow-hidden border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800">
        <Plot
          data={data}
          layout={layout}
          config={{
            displaylogo: false,
            responsive: true,
            toImageButtonOptions: {
              format: "png",
              filename: "pv_curve",
              height: 600,
              width: 900,
            },
            modeBarButtonsToRemove: ["select2d", "lasso2d"],
          }}
          style={{ width: "100%", height: "340px" }}
          useResizeHandler
        />
      </div>

      {/* Results stats */}
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
        <StatCard
          label="Load Margin"
          value={result.load_margin_mw != null ? `${result.load_margin_mw.toFixed(2)} MW` : "—"}
          accent
        />
        <StatCard
          label="Nose Voltage"
          value={result.nose_point_voltage != null ? `${result.nose_point_voltage.toFixed(4)} pu` : "—"}
        />
        <StatCard
          label="Steps"
          value={result.convergence_steps != null ? String(result.convergence_steps) : "—"}
        />
        <StatCard label="Grid"    value={formatGrid(result.grid)} />
        <StatCard label="Bus"     value={result.bus_id != null ? `Bus ${result.bus_id}` : "—"} />
        <StatCard label="PF"      value={result.power_factor != null ? result.power_factor.toFixed(2) : "—"} />
      </div>

      {/* Download PNG generated by backend */}
      {plotPath && (
        <a
          href={plotPath.startsWith("/") ? plotPath : `/${plotPath}`}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-2 text-xs text-indigo-600 dark:text-indigo-400 hover:underline"
        >
          ↓ Download server-side PNG
        </a>
      )}
    </div>
  );
}

// ─── Plotly builder ───────────────────────────────────────────────────────────

function buildPlot(result: ReturnType<typeof useAppStore.getState>["latestResult"], isDark: boolean) {
  const bg = isDark ? "#1f2937" : "#ffffff";
  const gridColor = isDark ? "#374151" : "#e5e7eb";
  const textColor = isDark ? "#d1d5db" : "#374151";
  const paperBg = isDark ? "#111827" : "#f9fafb";

  const traces: Plotly.Data[] = [];

  if (result?.voltage_upper && result?.load_upper) {
    traces.push({
      x: result.load_upper,
      y: result.voltage_upper,
      name: "Upper branch",
      type: "scatter",
      mode: "lines",
      line: { color: "#6366f1", width: 2.5 },
      hovertemplate: "Load: %{x:.3f} pu<br>Voltage: %{y:.4f} pu<extra></extra>",
    });
  }

  if (result?.voltage_lower && result?.load_lower) {
    traces.push({
      x: result.load_lower,
      y: result.voltage_lower,
      name: "Lower branch",
      type: "scatter",
      mode: "lines",
      line: { color: "#ef4444", width: 2.5, dash: "dot" },
      hovertemplate: "Load: %{x:.3f} pu<br>Voltage: %{y:.4f} pu<extra></extra>",
    });
  }

  // Nose point
  if (result?.nose_load != null && result?.nose_voltage != null) {
    traces.push({
      x: [result.nose_load],
      y: [result.nose_voltage],
      name: "Nose point",
      type: "scatter",
      mode: "text+markers" as const,
      marker: { color: "#f97316", size: 12, symbol: "circle", line: { color: "white", width: 2 } },
      text: ["Nose point"],
      textposition: "top right",
      hovertemplate: `Nose point<br>Load: ${(result.nose_load as number).toFixed(3)} pu<br>Voltage: ${(result.nose_voltage as number).toFixed(4)} pu<extra></extra>`,
    });
  }

  // Voltage limit line
  const maxLoad = getMaxLoad(result);
  if (result?.voltage_limit != null && maxLoad > 0) {
    traces.push({
      x: [0, maxLoad],
      y: [result.voltage_limit, result.voltage_limit],
      name: `Voltage limit (${(result.voltage_limit as number).toFixed(2)} pu)`,
      type: "scatter",
      mode: "lines",
      line: { color: "#fbbf24", width: 1.5, dash: "dash" },
      hoverinfo: "skip",
    });
  }

  const layout: Partial<Plotly.Layout> = {
    autosize: true,
    margin: { t: 30, b: 50, l: 60, r: 20 },
    paper_bgcolor: paperBg,
    plot_bgcolor: bg,
    xaxis: {
      title: { text: "Load (pu)", font: { color: textColor } },
      gridcolor: gridColor,
      tickfont: { color: textColor },
      zeroline: false,
    },
    yaxis: {
      title: { text: "Voltage (pu)", font: { color: textColor } },
      gridcolor: gridColor,
      tickfont: { color: textColor },
      zeroline: false,
      range: [0, 1.15],
    },
    legend: {
      font: { color: textColor },
      bgcolor: "transparent",
    },
    hovermode: "closest",
  };

  return { data: traces as Plotly.Data[], layout };
}

function getMaxLoad(result: ReturnType<typeof useAppStore.getState>["latestResult"]): number {
  if (!result) return 0;
  const loads = [...(result.load_upper ?? []), ...(result.load_lower ?? [])];
  return loads.length > 0 ? Math.max(...loads) : 0;
}

function formatGrid(grid?: unknown): string {
  if (typeof grid !== "string") return "—";
  return grid.replace("ieee", "IEEE ");
}

// ─── Stat card ────────────────────────────────────────────────────────────────

function StatCard({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) {
  return (
    <div className={`rounded-xl border p-3 space-y-0.5 ${
      accent
        ? "border-indigo-200 dark:border-indigo-800 bg-indigo-50 dark:bg-indigo-900/20"
        : "border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800"
    }`}>
      <p className="text-[11px] text-gray-500 dark:text-gray-400 uppercase tracking-wide">{label}</p>
      <p className={`font-semibold text-sm ${accent ? "text-indigo-700 dark:text-indigo-300" : "text-gray-800 dark:text-gray-200"}`}>
        {value}
      </p>
    </div>
  );
}
